kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: $($Namespace[$i])-devops
  namespace: $($Namespace[$i])
subjects:
- kind: Group
  name: 00000000-0000-0000-0000-000000000000
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: devops-reader-cluster-role #must match the name of the Role
  apiGroup: rbac.authorization.k8s.io