apiVersion: v1
kind: LimitRange
metadata:
  name: velero-mem-limit-range
  namespace: velero
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: velero-cpu-limit-range
  namespace: velero
spec:
  limits:
  - default:
      cpu: 1200m
    defaultRequest:
      cpu: 500m
    type: Container
---
apiVersion: v1
kind: Quota
metadata:
  name: velero
  namespace: velero
spec:
  hard:
    cpu: 1500m
    memory: 1Gi