kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: $($Namespace[$i])-devops
  namespace: $($Namespace[$i])
subjects:
- kind: Group
  name: 9c571fec-498a-4e08-bf7a-1998953428c9
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: devops-reader-cluster-role #must match the name of the Role
  apiGroup: rbac.authorization.k8s.io